# direnv integration (must be in interactive shells)
if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

# Secret helpers
if [[ -f "$HOME/.dotfiles/zsh/secrets.zsh" ]]; then
  source "$HOME/.dotfiles/zsh/secrets.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH_DISABLE_COMPFIX=true
export ZSH="$HOME/.oh-my-zsh"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
#Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
 zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
 zstyle ':omz:update' frequency 1

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(fzf git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
autoload -U compinit; compinit
eval "$(zoxide init zsh)"

export EDITOR='nvim'
# Aliases
## -- File Navigation --
alias cd="z"
alias ci="zi"
alias ls="eza --icons"

## -- Applications --
alias e="nvim"
alias dotedit="chezmoi edit"
alias dotfiles="chezmoi"
alias ..="cd .."
alias ...="cd ../.."

alias bhcli="/home/dasho/dev/bhcli-new/target/release/bhcli --refresh-rate 2 -m"
alias bhcli2="/home/dasho/dev/bhcli-new/target/release/bhcli --refresh-rate 2 --url http://blkh4ylofapg42tj6ht565klld5i42dhjtysvsnnswte4xt4uvnfj5qd.onion -m"
alias 404="/home/dasho/dev/bhcli-new/target/release/bhcli --refresh-rate 2 --url https://4-0-4.io/chat/min"
alias 404tor="/home/dasho/dev/bhcli-new/target/release/bhcli --refresh-rate 2 --url http://4o4o4hn4hsujpnbsso7tqigujuokafxys62thulbk2k3mf46vq22qfqd.onion/chat/min"
alias tb="cd /home/dasho/Downloads/tor-browser && ./start-tor-browser.desktop"

alias -s md="glow"
alias -s py="$EDITOR"
alias -s txt="bat"
alias -s log="bat"
alias -s json="bat"
alias -s xml="bat"
alias -s csv="bat"
alias -s yml="$EDITOR"
alias -s yaml="$EDITOR"
alias -s html="$EDITOR"
alias -s js="$EDITOR"
alias -s css="$EDITOR"
# alias -s sh="$EDITOR"
# alias -s zsh="$EDITOR"
alias -s conf="bat"
alias -s toml="bat"
alias -s rs="$EDITOR"
alias -s go="$EDITOR"
alias -s c="$EDITOR"
alias -s cpp="$EDITOR"
alias -s h="$EDITOR"
alias -s hpp="$EDITOR"
alias -s mov="open"
alias -s mp4="open"
alias -s mkv="open"
alias -s jpg="open"
alias -s png="open"
alias -s gif="open"

alias -g NE="2>/dev/null"
alias -g ND=">/dev/null"
alias -g NULL=">/dev/null 2>1"
alias -g F="| fzf"
alias -g T="| tail"
alias -g JQ="| jq"
alias -g G="| grep"
alias -g L="| less"
alias -g H="| head"

# Source and export variables from ~/.env
if [ -f ~/.env ]; then
    set -a
    source ~/.env
    set +a
fi
export PATH=$HOME/.local/bin:$PATH
export PATH="$HOME/.config/emacs/bin:$PATH"
export PATH="$HOME/Applications/halloy/bin:$PATH"

chpwd() {
    ls
}

clear_buffer_screen() {
  zle clear-screen
}
zle -N clear_buffer_screen
bindkey '^Xl' clear_buffer_screen

# --- Auto-start Zellij for interactive shells ---
# if [[ -o interactive ]] && [[ -z "$ZELLIJ" ]] && command -v zellij >/dev/null 2>&1; then
  # Attach to "main" if it exists, otherwise create it
  # exec zellij attach --create main
# fi
# --- End Auto-start Zellij ---
